"""Fixed escalation copy.

These are the highest-liability sentences in the product. They are here, as literal
strings, rather than generated by the model, because a red flag is exactly the moment
when a plausible-sounding paraphrase is most dangerous: when a rule fires, the drafted
LLM reply is thrown away and one of these is sent instead. The exact text shown is
persisted on the escalation row, so what the patient was told is recoverable years
later.

**Every entry is marked `sme_reviewed=False`.** The specification is explicit that
this copy must be written by a clinician, not by a developer and not by a model. What
follows is scaffolding that keeps the pipeline honest and testable — it says the
right kind of thing, in the right register, without diagnosing or prescribing — and
it is not signed off. `sme_reviewed` exists so that "not yet reviewed" is a visible
property of the data rather than an assumption, and so that a release gate can check
it. See docs/roadmap.md, SME question 3.

The copy obeys the conversational constraints in docs/safety-rules.md: it never
diagnoses, never names a probable cause, never estimates risk, never starts or
changes a medication, and never reassures once a rule has fired.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.domain.enums import Route
from app.domain.schemas import Finding


@dataclass(frozen=True)
class EscalationTemplate:
    """One fixed patient-facing message, keyed by rule or by route."""

    key: str
    text: str
    routes: tuple[Route, ...]
    sme_reviewed: bool = False


def _template(key: str, routes: tuple[Route, ...], text: str) -> EscalationTemplate:
    return EscalationTemplate(key=key, text=" ".join(text.split()), routes=routes)


TEMPLATES: dict[str, EscalationTemplate] = {
    # --- CALL 911 ---------------------------------------------------------
    "red_resp_distress": _template(
        "red_resp_distress",
        (Route.CALL_911,),
        """
        Based on what you've told me about your breathing, I need you to stop this
        check-in and call 911 now, or have someone call for you. Please don't drive
        yourself. I'm going to let your care team know we spoke.
        """,
    ),
    "red_chest_pain": _template(
        "red_chest_pain",
        (Route.CALL_911,),
        """
        Chest pain after surgery needs to be looked at right away. Please stop here
        and call 911 now, or have someone call for you. Don't drive yourself. I'm
        letting your care team know we spoke.
        """,
    ),
    "red_last": _template(
        "red_last",
        (Route.CALL_911,),
        """
        What you're describing can happen with the numbing medicine used in your nerve
        block, and it needs to be checked immediately. Please call 911 now, or have
        someone call for you. I'm notifying the anesthesia team as well.
        """,
    ),
    "red_oversedation": _template(
        "red_oversedation",
        (Route.CALL_911,),
        """
        If the patient is hard to wake, call 911 now. Stay with them and keep them on
        their side while you wait. I'm letting the care team know we spoke.
        """,
    ),
    "red_anaphylaxis": _template(
        "red_anaphylaxis",
        (Route.CALL_911,),
        """
        Swelling or a spreading rash with any breathing change needs emergency care
        right now. Please call 911, or have someone call for you. If you were given an
        epinephrine auto-injector and have been told how to use it, use it. I'm
        notifying your care team.
        """,
    ),
    "red_mh": _template(
        "red_mh",
        (Route.CALL_911,),
        """
        A fever along with muscle stiffness after anesthesia needs to be seen
        immediately. Please call 911 now, or have someone call for you, and tell them
        you had anesthesia within the last day. I'm notifying the anesthesia team.
        """,
    ),
    "red_suicidal_ideation": _template(
        "red_suicidal_ideation",
        (Route.CALL_911,),
        """
        Thank you for telling me that. I'm an automated check-in and I'm not able to
        help with this the way you deserve, so I'm stopping here and passing this to a
        person on your care team right now. If you're thinking about hurting yourself,
        please call or text 988, the Suicide and Crisis Lifeline, which is free and
        available 24 hours a day. If you're in immediate danger, please call 911.
        """,
    ),
    # --- GO TO THE EMERGENCY DEPARTMENT -----------------------------------
    "red_neuraxial_hematoma": _template(
        "red_neuraxial_hematoma",
        (Route.ED_NOW,),
        """
        New weakness, numbness, or loss of bladder or bowel control after a spinal or
        epidural needs to be checked in an emergency department right away — this is
        time-sensitive. Please have someone take you now, or call 911 if you can't get
        there. Tell them you had a spinal or epidural. I'm notifying the anesthesia
        team now.
        """,
    ),
    "red_compartment_syndrome": _template(
        "red_compartment_syndrome",
        (Route.ED_NOW,),
        """
        Pain that severe, especially with tightness or pain when the limb is moved,
        needs to be seen in an emergency department right away. Please go now, or call
        911 if you can't get there. Don't wait for your next pain medication dose.
        I'm notifying your surgical team.
        """,
    ),
    "red_pdph_with_red_flags": _template(
        "red_pdph_with_red_flags",
        (Route.ED_NOW,),
        """
        A headache like that, along with the other symptoms you've described, needs to
        be evaluated in an emergency department today. Please have someone take you
        now. Tell them you had a spinal or epidural. I'm notifying the anesthesia team.
        """,
    ),
    "red_ponv_intractable": _template(
        "red_ponv_intractable",
        (Route.ED_NOW,),
        """
        Not being able to keep any fluids down needs to be treated in person. Please
        go to an emergency department now, or have someone take you — you may need
        fluids through an IV. I'm notifying your care team.
        """,
    ),
    "red_dvt": _template(
        "red_dvt",
        (Route.ED_NOW,),
        """
        Pain and swelling in one calf after surgery needs to be checked in an
        emergency department today. Please have someone take you now rather than
        waiting. Try not to massage or rub the area. I'm notifying your surgical team.
        """,
    ),
    "red_syncope": _template(
        "red_syncope",
        (Route.ED_NOW,),
        """
        Fainting after surgery needs to be checked in person. Please have someone take
        you to an emergency department now — don't drive yourself. Stay lying down
        until they can get to you. I'm notifying your care team.
        """,
    ),
    "red_surgical_bleeding": _template(
        "red_surgical_bleeding",
        (Route.ED_NOW, Route.CALL_SURGEON),
        """
        That amount of bleeding needs to be seen right away. Press firmly on the
        dressing without removing it, and have someone take you to an emergency
        department now — or call 911 if the bleeding doesn't slow. I'm notifying your
        surgeon at the same time.
        """,
    ),
    # --- CALL ANESTHESIA ---------------------------------------------------
    "red_pdph_suspected": _template(
        "red_pdph_suspected",
        (Route.CALL_ANESTHESIA,),
        """
        A headache that's worse when you sit or stand and better when you lie flat is
        something the anesthesia team needs to know about today. I'm stopping the
        check-in here and notifying them now — someone will contact you. In the
        meantime, lie flat and keep drinking fluids. If the headache gets suddenly
        worse, or you develop vision changes, a stiff neck or a fever, go to an
        emergency department.
        """,
    ),
}


# Fallback copy keyed by route, for any rule with no message of its own. Deliberately
# vaguer than the rule-specific templates, since it cannot name what triggered it.
ROUTE_FALLBACKS: dict[Route, EscalationTemplate] = {
    Route.CALL_911: _template(
        "fallback_call_911",
        (Route.CALL_911,),
        """
        Based on what you've told me, please stop this check-in and call 911 now, or
        have someone call for you. I'm letting your care team know we spoke.
        """,
    ),
    Route.ED_NOW: _template(
        "fallback_ed_now",
        (Route.ED_NOW,),
        """
        Based on what you've told me, this needs to be looked at in person today.
        Please have someone take you to an emergency department now. I'm notifying
        your care team.
        """,
    ),
    Route.CALL_SURGEON: _template(
        "fallback_call_surgeon",
        (Route.CALL_SURGEON,),
        """
        I'm going to pass this to your surgeon's office so someone can follow up with
        you. If it gets worse before you hear from them, call them directly.
        """,
    ),
    Route.CALL_ANESTHESIA: _template(
        "fallback_call_anesthesia",
        (Route.CALL_ANESTHESIA,),
        """
        I'm going to pass this to the anesthesia team so someone can follow up with
        you. If it gets worse before you hear from them, call your care team directly.
        """,
    ),
    Route.ROUTINE: _template(
        "fallback_routine",
        (Route.ROUTINE,),
        """
        Thanks for telling me — I've made a note of that for your care team to review.
        """,
    ),
}


# Approved reassurance wording for expected findings, keyed by the GREEN rule that
# matched. Offered to the model as sanctioned language for a drafted reply rather
# than sent verbatim: a green finding does not stop the conversation, so the reply
# still has to fit the flow around it. Nothing here may be used once a rule has
# fired — see conversational constraint 3.
GREEN_REASSURANCE: dict[str, str] = {
    "green_sore_throat": (
        "A mild sore throat for a day or two afterwards is common and usually settles "
        "on its own."
    ),
    "green_hoarseness": (
        "A hoarse or croaky voice for a few days after anesthesia is common and "
        "usually settles on its own."
    ),
    "green_block_tingling": (
        "Pins and needles as the block wears off is the normal way feeling comes back."
    ),
    "green_grogginess": (
        "Feeling groggy or foggy on the day of surgery is expected, and it usually "
        "clears over the first day or so."
    ),
    "green_mild_nausea": (
        "Some queasiness afterwards is common, especially if it's settling and you're "
        "keeping fluids down."
    ),
}


def escalation_copy(finding: Finding) -> EscalationTemplate:
    """The exact text to send for `finding`.

    Falls back to route-level copy rather than raising, because a rule with a missing
    template must still produce a message — silence is the one unacceptable outcome
    when a red flag has fired. `tests/test_safety.py` asserts every RED rule resolves
    a template of its own, so the fallback is a safety net, not a routine path.
    """
    if finding.escalation_template_key:
        template = TEMPLATES.get(finding.escalation_template_key)
        if template is not None:
            return template
    return ROUTE_FALLBACKS[finding.routes[0]]


def unreviewed_template_keys() -> list[str]:
    """Templates no clinician has signed off. A release gate reads this."""
    return sorted(key for key, template in TEMPLATES.items() if not template.sme_reviewed)
